import { Question } from './types';

export const deepQuestions: Question[] = [
  {
    id: 'deep_sleep_brightness',
    category: 'sleep_pattern',
    mode: 'deep',
    title: '잠잘 때 방의 밝기에 대한 선호는?',
    type: 'single',
    options: [
      { id: 'complete_dark', text: '완전 암막(빛 거의 없음)', value: 'complete_dark', icon: '🌑' },
      { id: 'dim_light', text: '아주 은은한 불빛만', value: 'dim_light', icon: '🕯️' },
      { id: 'no_curtain', text: '커튼 안 쳐도 상관없음', value: 'no_curtain', icon: '🪟' },
      { id: 'mood_light', text: '간접조명·무드등 켜진 상태', value: 'mood_light', icon: '💡' },
      { id: 'varies', text: '상황에 따라 다르게', value: 'varies', icon: '🔄' },
      { id: 'ai_choice', text: '잘 모르겠어요', value: 'ai_choice', icon: '🤖' },
    ],
    required: true,
    weight: 1.5,
  },
  {
    id: 'deep_sleep_disturbance',
    category: 'sleep_pattern',
    mode: 'deep',
    title: '수면에 가장 방해가 되는 요소는?',
    type: 'single',
    options: [
      { id: 'noise', text: '소음(위·아래층, 도로 등)', value: 'noise', icon: '🔊' },
      { id: 'light', text: '빛(창문, 가로등 등)', value: 'light', icon: '💡' },
      { id: 'temperature', text: '온도(덥거나 추움)', value: 'temperature', icon: '🌡️' },
      { id: 'air', text: '공기(건조, 냄새, 답답함)', value: 'air', icon: '💨' },
      { id: 'bed', text: '침대·베개 등 물리적 불편', value: 'bed', icon: '🛏️' },
      { id: 'ai_choice', text: '정하기 어려워요', value: 'ai_choice', icon: '🤖' },
    ],
    required: true,
    weight: 2.0,
  },
  {
    id: 'deep_morning_first_10min',
    category: 'life_routine',
    mode: 'deep',
    title: '아침 일어난 후 첫 10분을 가장 편하게 보내고 싶은 공간은?',
    type: 'single',
    options: [
      { id: 'bed', text: '침대 머리맡(침실)', value: 'bed', icon: '🛏️' },
      { id: 'dressing', text: '화장대·드레스룸', value: 'dressing', icon: '👗' },
      { id: 'kitchen', text: '주방·식탁', value: 'kitchen', icon: '🍳' },
      { id: 'sofa', text: '거실 소파', value: 'sofa', icon: '🛋️' },
      { id: 'bathroom', text: '욕실(샤워, 세면)', value: 'bathroom', icon: '🚿' },
      { id: 'ai_choice', text: '상상이 안 돼요', value: 'ai_choice', icon: '🤖' },
    ],
    required: true,
    weight: 1.5,
  },
  {
    id: 'deep_physical_constraint',
    category: 'health_factors',
    mode: 'deep',
    title: '몸 상태 때문에 피하고 싶은 동작·자세는?',
    type: 'single',
    options: [
      { id: 'floor_sitting', text: '너무 낮은 좌식(바닥 앉기)', value: 'floor_sitting', icon: '🧘' },
      { id: 'squatting', text: '자주 쪼그려 앉기', value: 'squatting', icon: '🦵' },
      { id: 'reaching_high', text: '높은 곳 팔 들기', value: 'reaching_high', icon: '🙋' },
      { id: 'stairs', text: '계단·단 차이 오르내리기', value: 'stairs', icon: '🪜' },
      { id: 'none', text: '특별히 피할 동작 없음', value: 'none', icon: '✅' },
      { id: 'ai_choice', text: '판단 어려워요', value: 'ai_choice', icon: '🤖' },
    ],
    required: false,
    weight: 1.5,
  },
  {
    id: 'deep_seasonal_usage',
    category: 'life_routine',
    mode: 'deep',
    title: '계절에 따라 집 사용 방식이 어떻게 달라지나요?',
    type: 'single',
    options: [
      { id: 'summer_living_winter_bedroom', text: '여름엔 거실, 겨울엔 침실', value: 'summer_living_winter_bedroom', icon: '🌞❄️' },
      { id: 'changes_often', text: '계절마다 쓰는 방 자주 바뀜', value: 'changes_often', icon: '🔄' },
      { id: 'consistent', text: '사계절 비슷하게 사용', value: 'consistent', icon: '📅' },
      { id: 'hvac_issue', text: '냉난방 위치 때문에 불편', value: 'hvac_issue', icon: '🌡️' },
      { id: 'balcony_varies', text: '베란다 활용도 크게 달라짐', value: 'balcony_varies', icon: '🪴' },
      { id: 'ai_choice', text: '패턴 파악 어려워요', value: 'ai_choice', icon: '🤖' },
    ],
    required: false,
    weight: 1.0,
  },
  {
    id: 'deep_organization_style',
    category: 'organization_habit',
    mode: 'deep',
    title: '정리·수납에 대한 본인 스타일은?',
    type: 'single',
    options: [
      { id: 'minimalist', text: '물건 줄이는 미니멀리스트', value: 'minimalist', icon: '⚪' },
      { id: 'categorizer', text: '카테고리별 정리 선호', value: 'categorizer', icon: '📦' },
      { id: 'hide_all', text: '수납장에 깔끔히 숨기기', value: 'hide_all', icon: '🚪' },
      { id: 'messy_now', text: '지금 어질러져있고 바꾸고 싶음', value: 'messy_now', icon: '🌪️' },
      { id: 'family_influenced', text: '가족 습관에 영향 많이 받음', value: 'family_influenced', icon: '👨‍👩‍👧' },
      { id: 'ai_choice', text: '설명 어려워요', value: 'ai_choice', icon: '🤖' },
    ],
    required: true,
    weight: 1.5,
  },
  {
    id: 'deep_electronics_location',
    category: 'activity_flow',
    mode: 'deep',
    title: '전자기기(모니터, 스피커, 콘센트)가 많이 몰린 공간은?',
    type: 'single',
    options: [
      { id: 'living_tv', text: '거실 TV 주변', value: 'living_tv', icon: '📺' },
      { id: 'workspace', text: '작업방·서재', value: 'workspace', icon: '💻' },
      { id: 'bedroom', text: '침실(충전기, TV 등)', value: 'bedroom', icon: '🛏️' },
      { id: 'kitchen', text: '주방(가전 등)', value: 'kitchen', icon: '🍳' },
      { id: 'distributed', text: '집 전체 분산', value: 'distributed', icon: '🔌' },
      { id: 'ai_choice', text: '인식 안 돼요', value: 'ai_choice', icon: '🤖' },
    ],
    required: false,
    weight: 1.0,
  },
  {
    id: 'deep_bathroom_usage',
    category: 'life_routine',
    mode: 'deep',
    title: '욕실 사용 방식에 가장 가까운 것은?',
    type: 'single',
    options: [
      { id: 'quick_shower', text: '5분 안에 끝내는 샤워', value: 'quick_shower', icon: '🚿' },
      { id: 'shower_plus', text: '샤워 + 피로회복', value: 'shower_plus', icon: '🧖' },
      { id: 'bath_spa', text: '반신욕·홈스파', value: 'bath_spa', icon: '🛁' },
      { id: 'makeup', text: '출근 준비·메이크업 공간', value: 'makeup', icon: '💄' },
      { id: 'shared', text: '가족 공용으로 동선 중요', value: 'shared', icon: '👨‍👩‍👧‍👦' },
      { id: 'ai_choice', text: '잘 모르겠어요', value: 'ai_choice', icon: '🤖' },
    ],
    required: false,
    weight: 1.0,
  },
  {
    id: 'deep_cooking_stress',
    category: 'discomfort_factors',
    mode: 'deep',
    title: '요리할 때 가장 스트레스 받는 요소는?',
    type: 'single',
    options: [
      { id: 'small_space', text: '조리 공간·작업대 부족', value: 'small_space', icon: '📐' },
      { id: 'storage', text: '수납 부족으로 불편', value: 'storage', icon: '📦' },
      { id: 'ventilation', text: '환기(냄새, 연기)', value: 'ventilation', icon: '💨' },
      { id: 'flow', text: '설거지·정리 동선 비효율', value: 'flow', icon: '🚶' },
      { id: 'crowded', text: '여러 사람 동시 사용 어려움', value: 'crowded', icon: '👥' },
      { id: 'ai_choice', text: '설명 힘들어요', value: 'ai_choice', icon: '🤖' },
    ],
    required: false,
    weight: 1.0,
  },
  {
    id: 'deep_smell_concern',
    category: 'sensory_sensitivity',
    mode: 'deep',
    title: '집 안에서 냄새가 가장 신경 쓰이는 곳은?',
    type: 'single',
    options: [
      { id: 'entrance', text: '현관(신발장 등)', value: 'entrance', icon: '👞' },
      { id: 'kitchen', text: '주방(요리, 쓰레기)', value: 'kitchen', icon: '🗑️' },
      { id: 'bathroom', text: '욕실(배수, 곰팡이)', value: 'bathroom', icon: '🚿' },
      { id: 'closet', text: '옷방·드레스룸', value: 'closet', icon: '👗' },
      { id: 'living_air', text: '거실·전체 공기', value: 'living_air', icon: '💨' },
      { id: 'ai_choice', text: '떠오르지 않아요', value: 'ai_choice', icon: '🤖' },
    ],
    required: false,
    weight: 1.0,
  },
  {
    id: 'deep_allergy',
    category: 'health_factors',
    mode: 'deep',
    title: '알레르기나 공기질 때문에 신경 쓰이는 부분은?',
    type: 'single',
    options: [
      { id: 'dust_mite', text: '집먼지·진드기', value: 'dust_mite', icon: '🦠' },
      { id: 'mold', text: '곰팡이·습기', value: 'mold', icon: '💧' },
      { id: 'pet', text: '반려동물 털·비듬', value: 'pet', icon: '🐕' },
      { id: 'outdoor', text: '외부 미세먼지·환기', value: 'outdoor', icon: '🌫️' },
      { id: 'general_interest', text: '알레르기 없지만 공기질 관심', value: 'general_interest', icon: '🌬️' },
      { id: 'ai_choice', text: '잘 모르겠어요', value: 'ai_choice', icon: '🤖' },
    ],
    required: false,
    weight: 1.0,
  },
  {
    id: 'deep_lighting_change',
    category: 'lighting_preference',
    mode: 'deep',
    title: '현재 조명 사용 상태와 바꾸고 싶은 방향은?',
    type: 'single',
    options: [
      { id: 'want_indirect', text: '전체등만 있음 → 간접조명 추가', value: 'want_indirect', icon: '💡' },
      { id: 'want_brighter', text: '어두움 → 더 밝게', value: 'want_brighter', icon: '☀️' },
      { id: 'want_warmer', text: '너무 밝고 차가움 → 따뜻하게', value: 'want_warmer', icon: '🔥' },
      { id: 'already_good', text: '이미 간접조명 씀 → 더 체계적으로', value: 'already_good', icon: '✨' },
      { id: 'basic_only', text: '조명은 기본만', value: 'basic_only', icon: '⚪' },
      { id: 'ai_choice', text: '조명 계획 어려워요', value: 'ai_choice', icon: '🤖' },
    ],
    required: false,
    weight: 1.0,
  },
  {
    id: 'deep_work_hours',
    category: 'life_routine',
    mode: 'deep',
    title: '집에서 일(재택근무·공부·작업)하는 시간은?',
    type: 'single',
    options: [
      { id: 'almost_none', text: '거의 하지 않음', value: 'almost_none', icon: '🚫' },
      { id: 'under_1h', text: '하루 1시간 미만', value: 'under_1h', icon: '⏰' },
      { id: '1_3h', text: '하루 1~3시간', value: '1_3h', icon: '⏱️' },
      { id: '3_6h', text: '하루 3~6시간', value: '3_6h', icon: '⏲️' },
      { id: 'over_6h', text: '하루 6시간 이상', value: 'over_6h', icon: '💻' },
      { id: 'ai_choice', text: '고정 안 돼있어요', value: 'ai_choice', icon: '🤖' },
    ],
    required: false,
    weight: 1.0,
  },
  {
    id: 'deep_guest_frequency',
    category: 'family_composition',
    mode: 'deep',
    title: '손님(친구·지인·고객)이 집에 오는 빈도는?',
    type: 'single',
    options: [
      { id: 'rarely', text: '거의 오지 않음', value: 'rarely', icon: '🚫' },
      { id: 'monthly_less', text: '한 달에 1번 이하', value: 'monthly_less', icon: '📅' },
      { id: 'monthly_2_3', text: '한 달에 2~3번', value: 'monthly_2_3', icon: '📆' },
      { id: 'weekly', text: '주 1회 이상', value: 'weekly', icon: '🗓️' },
      { id: 'want_but_cant', text: '초대하고 싶지만 집 상태 때문에 망설임', value: 'want_but_cant', icon: '😔' },
      { id: 'ai_choice', text: '정확히 모르겠어요', value: 'ai_choice', icon: '🤖' },
    ],
    required: false,
    weight: 1.0,
  },
  {
    id: 'deep_future_3_5_years',
    category: 'life_routine',
    mode: 'deep',
    title: '3~5년 뒤 이 집에서 가장 가능성 큰 변화는?',
    type: 'single',
    options: [
      { id: 'children_growth', text: '자녀 출산·성장', value: 'children_growth', icon: '👶' },
      { id: 'family_change', text: '부모님·가족 구성 변화', value: 'family_change', icon: '👴' },
      { id: 'remote_work', text: '재택·업무공간 비중 증가', value: 'remote_work', icon: '💻' },
      { id: 'moving_plan', text: '이사 계획 있음', value: 'moving_plan', icon: '🏠' },
      { id: 'stable', text: '큰 변화 없이 지금 구조 유지', value: 'stable', icon: '✅' },
      { id: 'ai_choice', text: '장기 계획 불명확', value: 'ai_choice', icon: '🤖' },
    ],
    required: false,
    weight: 1.0,
  },
  {
    id: 'deep_health_goal',
    category: 'health_factors',
    mode: 'deep',
    title: '이 집이 나를 더 건강하게 만들었으면 하는 부분은?',
    type: 'single',
    options: [
      { id: 'sleep', text: '수면(깊은 잠, 리듬)', value: 'sleep', icon: '😴' },
      { id: 'meal', text: '식사 습관', value: 'meal', icon: '🍽️' },
      { id: 'exercise', text: '운동·스트레칭', value: 'exercise', icon: '🏃' },
      { id: 'mental', text: '정신적 휴식·스트레스 감소', value: 'mental', icon: '🧘' },
      { id: 'family', text: '가족 관계·대화 시간', value: 'family', icon: '👨‍👩‍👧' },
      { id: 'ai_choice', text: '한 가지로 못 정해요', value: 'ai_choice', icon: '🤖' },
    ],
    required: false,
    weight: 1.5,
  },
  {
    id: 'deep_keep_unchanged',
    category: 'space_sense',
    mode: 'deep',
    title: '현재 집에서 절대 건드리지 않았으면 하는 것은?',
    type: 'single',
    options: [
      { id: 'old_furniture', text: '오래된 가구·추억의 물건', value: 'old_furniture', icon: '🪑' },
      { id: 'room_structure', text: '특정 방의 구조·위치', value: 'room_structure', icon: '🏠' },
      { id: 'materials', text: '마음에 드는 마감재·자재', value: 'materials', icon: '🎨' },
      { id: 'storage', text: '수납 구조(붙박이장 등)', value: 'storage', icon: '📦' },
      { id: 'open_to_change', text: '대부분 바꿀 의향 있음', value: 'open_to_change', icon: '🔄' },
      { id: 'ai_choice', text: '정리 안 돼요', value: 'ai_choice', icon: '🤖' },
    ],
    required: false,
    weight: 1.0,
  },
  {
    id: 'deep_habit_change',
    category: 'life_routine',
    mode: 'deep',
    title: '이번 인테리어를 계기로 바꾸고 싶은 생활 습관은?',
    type: 'single',
    options: [
      { id: 'minimal_living', text: '물건 덜 사기, 미니멀하게', value: 'minimal_living', icon: '⚪' },
      { id: 'regular_cleaning', text: '정기적 정리·청소', value: 'regular_cleaning', icon: '🧹' },
      { id: 'focus_work', text: '집에서 일·공부 집중', value: 'focus_work', icon: '📚' },
      { id: 'family_time', text: '가족과 시간 늘리기', value: 'family_time', icon: '👨‍👩‍👧' },
      { id: 'invite_guests', text: '사람 초대하기 편한 공간', value: 'invite_guests', icon: '🎉' },
      { id: 'ai_choice', text: '하나로 정하기 어려워요', value: 'ai_choice', icon: '🤖' },
    ],
    required: false,
    weight: 1.0,
  },
];

