import { Question } from './types';

export const standardQuestions: Question[] = [
  {
    id: 'standard_main_space',
    category: 'space_sense',
    mode: 'standard',
    title: '집에서 하루 중 가장 오래 머무는 공간은 어디인가요?',
    type: 'single',
    options: [
      { id: 'living_room', text: '거실', value: 'living_room', icon: '🛋️' },
      { id: 'kitchen', text: '주방·식탁', value: 'kitchen', icon: '🍽️' },
      { id: 'bedroom', text: '침실', value: 'bedroom', icon: '🛏️' },
      { id: 'workspace', text: '작업방·서재', value: 'workspace', icon: '📚' },
      { id: 'kids_room', text: '아이방·놀이방', value: 'kids_room', icon: '🧸' },
      { id: 'ai_choice', text: '별도 선호는 없습니다. AI 추천을 따르겠습니다', value: 'ai_choice', icon: '🤖' },
    ],
    required: true,
    weight: 1.5,
  },
  {
    id: 'standard_daily_discomfort',
    category: 'discomfort_factors',
    mode: 'standard',
    title: '현재 집에서 "매일 불편하지만 참고 넘어가는 것"에 가장 가까운 것은 무엇인가요?',
    type: 'single',
    options: [
      { id: 'storage', text: '수납공간 부족 (물건 정리가 안 됨)', value: 'storage', icon: '📦' },
      { id: 'flow', text: '동선이 불편함 (돌아다니기, 요리, 세탁 등)', value: 'flow', icon: '🚶' },
      { id: 'lighting', text: '조명·채광이 답답함 또는 눈부심', value: 'lighting', icon: '💡' },
      { id: 'materials', text: '마감재·색감이 마음에 안 듦', value: 'materials', icon: '🎨' },
      { id: 'layout', text: '가구 배치가 어색하고 공간이 좁게 느껴짐', value: 'layout', icon: '📐' },
      { id: 'ai_choice', text: '하나만 고르기 애매합니다. 이 부분은 AI가 대신 정합니다', value: 'ai_choice', icon: '🤖' },
    ],
    required: true,
    weight: 2.0,
  },
  {
    id: 'standard_cleaning_style',
    category: 'cleaning_preference',
    mode: 'standard',
    title: '청소와 정리에 대한 본인 스타일에 가장 가까운 것은?',
    type: 'single',
    options: [
      { id: 'frequent_messy', text: '자주 치우지만 금방 다시 어지러워짐', value: 'frequent_messy', icon: '🔄' },
      { id: 'batch_clean', text: '주말이나 특정 날에 몰아서 정리', value: 'batch_clean', icon: '📅' },
      { id: 'only_when_bad', text: '눈에 너무 거슬릴 때만 치움', value: 'only_when_bad', icon: '👀' },
      { id: 'system_needed', text: '정리 시스템만 잘 만들어주면 유지할 자신 있음', value: 'system_needed', icon: '✅' },
      { id: 'hide_all', text: '정리·수납은 최대한 단순했으면 좋겠음(수납장에 다 숨기기)', value: 'hide_all', icon: '🚪' },
      { id: 'ai_choice', text: '헷갈리는 편이에요. 이 부분은 인테리봇에 맡길게요', value: 'ai_choice', icon: '🤖' },
    ],
    required: true,
    weight: 1.5,
  },
  {
    id: 'standard_family_time',
    category: 'family_composition',
    mode: 'standard',
    title: '가족이 한자리에 가장 자주 모이는 시간대와 장소는 언제, 어디인가요?',
    type: 'single',
    options: [
      { id: 'weekday_living', text: '평일 저녁, 거실', value: 'weekday_living', icon: '🌙' },
      { id: 'weekday_kitchen', text: '평일 저녁, 주방·식탁', value: 'weekday_kitchen', icon: '🍽️' },
      { id: 'weekend_living', text: '주말 오후, 거실', value: 'weekend_living', icon: '☀️' },
      { id: 'weekend_kitchen', text: '주말, 주방·식탁', value: 'weekend_kitchen', icon: '🥘' },
      { id: 'separate', text: '거의 각자 방을 쓰고 함께 모이는 시간이 적음', value: 'separate', icon: '🚪' },
      { id: 'ai_choice', text: '딱 집어서 말하긴 어려워요. 이 부분은 인테리봇이 패턴을 잡아줘요', value: 'ai_choice', icon: '🤖' },
    ],
    required: true,
    weight: 1.5,
  },
  {
    id: 'standard_kids_pets',
    category: 'family_composition',
    mode: 'standard',
    title: '아이 또는 반려동물이 있다면, 그들의 공간에 대한 선호에 가장 가까운 것은?',
    type: 'single',
    options: [
      { id: 'open_free', text: '아이·반려동물이 자유롭게 돌아다닐 수 있게 개방형으로 쓰고 싶다', value: 'open_free', icon: '🏃' },
      { id: 'dedicated_spot', text: '거실·공용공간에 전용 자리(하우스, 매트 등)를 만들어주고 싶다', value: 'dedicated_spot', icon: '🐾' },
      { id: 'hidden_storage', text: '아이·반려동물의 물건은 최대한 깔끔하게 수납하고 싶다', value: 'hidden_storage', icon: '📦' },
      { id: 'dedicated_room', text: '특정 방(아이방, 펫룸 등)을 중심 공간으로 만들고 싶다', value: 'dedicated_room', icon: '🚪' },
      { id: 'none', text: '아이·반려동물은 없다 / 인테리어에 크게 반영하지 않아도 된다', value: 'none', icon: '🚫' },
      { id: 'ai_choice', text: '고민이 길어질 것 같아요. 인테리봇한테 넘길게요', value: 'ai_choice', icon: '🤖' },
    ],
    required: false,
    weight: 1.0,
  },
  {
    id: 'standard_daily_scene',
    category: 'life_routine',
    mode: 'standard',
    title: '인테리어 후, 가장 먼저 바뀌었으면 하는 "하루의 장면"은 무엇인가요?',
    type: 'single',
    options: [
      { id: 'morning_prep', text: '아침 준비 시간(세면, 옷 고르기, 주방 동선 등)', value: 'morning_prep', icon: '🌅' },
      { id: 'after_work', text: '퇴근 후 소파에 앉는 순간', value: 'after_work', icon: '🛋️' },
      { id: 'family_meal', text: '가족이 함께 식사하는 시간', value: 'family_meal', icon: '🍽️' },
      { id: 'personal_time', text: '개인 취미·작업·공부 시간', value: 'personal_time', icon: '📚' },
      { id: 'guest_visit', text: '손님이 왔을 때 집을 보여주는 순간', value: 'guest_visit', icon: '🚪' },
      { id: 'ai_choice', text: '어느 한 장면으로 고르기 애매합니다. 이 부분은 AI가 대신 정합니다', value: 'ai_choice', icon: '🤖' },
    ],
    required: true,
    weight: 1.5,
  },
  {
    id: 'standard_budget_priority',
    category: 'budget_sense',
    mode: 'standard',
    title: '예산을 생각할 때 가장 우선순위를 두고 싶은 부분은 어디인가요?',
    type: 'single',
    options: [
      {
        id: 'structure',
        text: '구조·동선 변경(벽체, 문, 가벽 등)',
        value: 'structure',
        icon: '🏗️',
      },
      {
        id: 'materials',
        text: '마감재·자재(바닥, 벽, 타일, 위생도기 등)',
        value: 'materials',
        icon: '🧱',
      },
      {
        id: 'storage',
        text: '가구·수납(붙박이장, 제작가구 등)',
        value: 'storage',
        icon: '🧺',
      },
      {
        id: 'lighting',
        text: '조명·색감·분위기 연출',
        value: 'lighting',
        icon: '💡',
      },
      {
        id: 'balance',
        text: '전체 밸런스(특정 한 곳보다 전반적인 균형)',
        value: 'balance',
        icon: '⚖️',
      },
      {
        id: 'ai',
        text: '예산 배분이 어렵네요. 인테리봇 AI가 나중에 보완합니다.',
        value: 'ai-fallback',
        icon: '🤖',
      },
    ],
    required: true,
    weight: 2.0,
  },
  {
    id: 'standard_lifestyle_change',
    category: 'life_routine',
    mode: 'standard',
    title: '앞으로 3년 안에 라이프스타일이 크게 달라질 가능성이 있는 요소는 무엇인가요?',
    type: 'single',
    options: [
      { id: 'children', text: '출산·자녀 성장(입학 등)', value: 'children', icon: '👶' },
      { id: 'parents', text: '부모님과 동거 또는 장기 방문', value: 'parents', icon: '👴' },
      { id: 'remote_work', text: '재택근무·재택 비율 증가', value: 'remote_work', icon: '💻' },
      { id: 'career_change', text: '창업·이직 등으로 생활 패턴 변화', value: 'career_change', icon: '🚀' },
      { id: 'stable', text: '크게 달라질 계획 없음', value: 'stable', icon: '✅' },
      { id: 'ai_choice', text: '아직 확실하지 않아요. 이런 부분은 AI가 시나리오로 반영합니다', value: 'ai_choice', icon: '🤖' },
    ],
    required: false,
    weight: 1.0,
  },
  {
    id: 'standard_personal_space',
    category: 'hobby_lifestyle',
    mode: 'standard',
    title: '"이 집에서 나만을 위한 자리"를 만든다면, 어디에 가장 가깝나요?',
    type: 'single',
    options: [
      { id: 'reading_chair', text: '조용히 앉을 수 있는 1인용 의자·코너', value: 'reading_chair', icon: '🪑' },
      { id: 'desk_space', text: '작업·공부·창작을 할 수 있는 책상 공간', value: 'desk_space', icon: '📝' },
      { id: 'hobby_display', text: '취미(피규어, 악기, 책, 컬렉션 등)를 전시하는 공간', value: 'hobby_display', icon: '🎸' },
      { id: 'bedroom_corner', text: '침대 머리맡, 침실 일부를 나만의 구역으로', value: 'bedroom_corner', icon: '🛏️' },
      { id: 'separate_room', text: '별도의 작은 방(서재, 취미방 등)', value: 'separate_room', icon: '🚪' },
      { id: 'ai_choice', text: '딱 떠오르는 그림이 없어요. 인테리봇이 제안해줘요', value: 'ai_choice', icon: '🤖' },
    ],
    required: false,
    weight: 1.0,
  },
  {
    id: 'standard_compliment',
    category: 'home_purpose',
    mode: 'standard',
    title: '인테리어가 끝난 후, 지인들에게 가장 듣고 싶은 말은 무엇인가요?',
    type: 'single',
    options: [
      { id: 'comfortable', text: '"되게 편해 보인다, 살기 좋겠다"', value: 'comfortable', icon: '😌' },
      { id: 'luxurious', text: '"호텔 같아, 진짜 고급스럽다"', value: 'luxurious', icon: '✨' },
      { id: 'suits_you', text: '"와, 진짜 너 같다. 너랑 잘 어울린다"', value: 'suits_you', icon: '👍' },
      { id: 'detailed', text: '"센스 미쳤다, 디테일이 다르네"', value: 'detailed', icon: '🎨' },
      { id: 'worth_it', text: '"생각보다 비용 잘 쓴 것 같다, 돈 안 아깝겠다"', value: 'worth_it', icon: '💰' },
      { id: 'ai_choice', text: '어떤 말이든 괜찮아요. 해석은 인테리봇 AI가 알아서 합니다', value: 'ai_choice', icon: '🤖' },
    ],
    required: false,
    weight: 1.0,
  },
];
