import { Question } from './types';

export const vibeQuestions: Question[] = [
  {
    id: 'vibe_weekend_alone',
    category: 'hobby_lifestyle',
    mode: 'vibe',
    title: '주말 오후, 아무 방해 없이 혼자 있을 수 있다면 집에서 가장 하고 싶은 것은?',
    type: 'single',
    options: [
      { id: 'streaming', text: '넷플릭스·유튜브 정주행', value: 'streaming', icon: '📺' },
      { id: 'music_chill', text: '음악 켜놓고 멍 때리기', value: 'music_chill', icon: '🎵' },
      { id: 'study_plan', text: '책·노트·정리·계획', value: 'study_plan', icon: '📚' },
      { id: 'cooking', text: '요리·베이킹·커피', value: 'cooking', icon: '🍳' },
      { id: 'party', text: '친구 불러 홈파티', value: 'party', icon: '🎉' },
      { id: 'ai_choice', text: '그때그때 달라요', value: 'ai_choice', icon: '🤖' },
    ],
    required: true,
    weight: 1.5,
  },
  {
    id: 'vibe_cafe_seat',
    category: 'space_sense',
    mode: 'vibe',
    title: '카페에 갔을 때 가장 자주 선택하는 자리는?',
    type: 'single',
    options: [
      { id: 'window', text: '창가 자리', value: 'window', icon: '🪟' },
      { id: 'corner', text: '벽 쪽 구석', value: 'corner', icon: '🏠' },
      { id: 'center', text: '중앙 큰 테이블', value: 'center', icon: '🪑' },
      { id: 'bar', text: '바(Bar) 좌석', value: 'bar', icon: '🍷' },
      { id: 'terrace', text: '야외 테라스', value: 'terrace', icon: '🌳' },
      { id: 'ai_choice', text: '딱 정해진 자리 없어요', value: 'ai_choice', icon: '🤖' },
    ],
    required: true,
    weight: 1.0,
  },
  {
    id: 'vibe_sns_interior',
    category: 'color_preference',
    mode: 'vibe',
    title: 'SNS에서 더 자주 저장하는 인테리어 이미지는?',
    type: 'single',
    options: [
      { id: 'white_minimal', text: '하얗고 깨끗한 미니멀', value: 'white_minimal', icon: '⚪' },
      { id: 'nordic_natural', text: '우드와 식물 북유럽', value: 'nordic_natural', icon: '🌿' },
      { id: 'bold_color', text: '강한 컬러 포인트', value: 'bold_color', icon: '🎨' },
      { id: 'hotel_luxury', text: '호텔·라운지 럭셔리', value: 'hotel_luxury', icon: '✨' },
      { id: 'industrial', text: '공장형·러프', value: 'industrial', icon: '🏭' },
      { id: 'ai_choice', text: '스크랩이 잡다해요', value: 'ai_choice', icon: '🤖' },
    ],
    required: true,
    weight: 1.5,
  },
  {
    id: 'vibe_travel_style',
    category: 'hobby_lifestyle',
    mode: 'vibe',
    title: '지금 당장 떠나고 싶은 여행 스타일은?',
    type: 'single',
    options: [
      { id: 'city', text: '서울·뉴욕 대도시', value: 'city', icon: '🏙️' },
      { id: 'nature', text: '산·바다·숲', value: 'nature', icon: '🏞️' },
      { id: 'town', text: '조용한 소도시', value: 'town', icon: '🏘️' },
      { id: 'resort', text: '리조트·호캉스', value: 'resort', icon: '🏖️' },
      { id: 'culture', text: '카페·미술관·편집숍', value: 'culture', icon: '☕' },
      { id: 'ai_choice', text: '정하지 못하겠어요', value: 'ai_choice', icon: '🤖' },
    ],
    required: true,
    weight: 1.0,
  },
  {
    id: 'vibe_home_relationship',
    category: 'home_purpose',
    mode: 'vibe',
    title: '집이 사람이라면, 당신과의 관계는 어떤 느낌이면 좋겠나요?',
    type: 'single',
    options: [
      { id: 'best_friend', text: '편한 찐친', value: 'best_friend', icon: '🤝' },
      { id: 'supporter', text: '든든한 동료', value: 'supporter', icon: '💪' },
      { id: 'trainer', text: '성장시키는 트레이너', value: 'trainer', icon: '🏋️' },
      { id: 'lover', text: '특별하게 만드는 연인', value: 'lover', icon: '💕' },
      { id: 'coach', text: '다시 시작하게 하는 코치', value: 'coach', icon: '🎯' },
      { id: 'ai_choice', text: '한 가지로 정의 못해요', value: 'ai_choice', icon: '🤖' },
    ],
    required: true,
    weight: 1.5,
  },
  {
    id: 'vibe_movie_genre',
    category: 'home_purpose',
    mode: 'vibe',
    title: '집 전체 분위기를 영화 장르로 고르자면?',
    type: 'single',
    options: [
      { id: 'healing_drama', text: '힐링 드라마', value: 'healing_drama', icon: '🌸' },
      { id: 'romcom', text: '로맨틱 코미디', value: 'romcom', icon: '💝' },
      { id: 'growth', text: '차분한 성장 영화', value: 'growth', icon: '🌱' },
      { id: 'noir', text: '스타일리시 느와르', value: 'noir', icon: '🕶️' },
      { id: 'documentary', text: '현실감 있는 일상', value: 'documentary', icon: '📹' },
      { id: 'ai_choice', text: '장르로 설명 어려워요', value: 'ai_choice', icon: '🤖' },
    ],
    required: true,
    weight: 1.0,
  },
];

